### ISSUE TITLE
nodePublicKey is not return from method getNodePeers.

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/symbol-sdk-typescript-javascript#806]
The method `getNodePeers()` return `nodePublicKey` undefined.
 
![image](https://user-images.githubusercontent.com/5649156/127505747-5d6c3283-f398-4685-9a4c-d39880b2e430.png)

![image](https://user-images.githubusercontent.com/5649156/127564304-7d873d8f-eb66-4c7a-9aee-c7512029de2d.png)

**Comment by fboucquez** [comment]
This is a known issue.  

Rest injects the nodePublicKey to /node/info from the configuration. But it doesn't know the nodePublicKey of the peers so SDK doesn't either. 

http://ngl-dual-101.testnet.symboldev.network:3000/node/info (the nodePublicKey is known)
http://ngl-dual-101.testnet.symboldev.network:3000/node/peers (the peers' nodePublicKey are unknown)

We have had conversations about how peers can share the node public keys so people can delegate harvest to them, especially if the node is a peer-only one. The node public key is not part of the information the peers share with each other. In this case, the user would need to enter the public key manually if it's not found....

**Comment by rg911** [comment]
those are different nodes right?
node/peers returns the pear node,

**Comment by AnthonyLaw** [comment]
> those are different nodes right?
> node/peers returns the pear node,

you are right, I just updated the image.

**Comment by AnthonyLaw** [comment]
> This is a known issue.
> 
> Rest injects the nodePublicKey to /node/info from the configuration. But it doesn't know the nodePublicKey of the peers so SDK doesn't either.
> 
> http://ngl-dual-101.testnet.symboldev.network:3000/node/info (the nodePublicKey is known)
> http://ngl-dual-101.testnet.symboldev.network:3000/node/peers (the peers' nodePublicKey are unknown)
> 
> We have had conversations about how peers can share the node public keys so people can delegate harvest to them, especially if the node is a peer-only one. The node public key is not part of the information the peers share with each other. In this case, the user would need to enter the public key manually if it's not found....

I see, i will close this for now :)
thanks mate.
