### ISSUE TITLE
Support for Custom Headers

### ISSUE THREAD

**Issue by vietnamese-chowder** [symbol/symbol-sdk-typescript-javascript#842]
1. Expected behavior and actual behavior.
`RepositoryFactoryConfig` should have an optional field `headers` that is used during `createAccountRepository`, `createBlockRepository`, etc., so that at `AccountRoutesApi.getAccountInfoRaw`, for example, you could have 

```
const headerParameters: runtime.HTTPHeaders = this.headers ?? {};
```
This is required for authentication with BaaS nodes. In my case it's like `{ 'x-api-key': '<MY_API_KEY>' }`

2. Steps to reproduce the problem.
Try creating a new `RepositoryFactoryHttp` with a headers field in configs.

3. Specifications like the version of the project, operating system, or hardware.
```
"symbol-sdk": "^2.0.1",
```

**Comment by yilmazbahadir** [comment]
Hi @vietnamese-chowder, thanks for reporting this.

I can see that you need to pass headers to every request. 

Could you try to set the `fetchApi` parameter in the `RepositoryFactoryConfig` with the wrapped `FetchApi` as described in the link below while creating the `RepositoryFactoryHttp`?

https://stackoverflow.com/a/56257966/3190131

**Comment by vietnamese-chowder** [comment]
Thanks! That works

**Comment by vietnamese-chowder** [comment]
I should note, though, that this was causing `CORS Missing Allow Header` errors and I had to set up a proxy in webpack like the following to make it go away
```
devServer: {
  static: path.join(process.cwd(), "build"),
  proxy: {
    '/api/xym': {
      target: '<MY_URL>',
      secure: false,
      pathRewrite: {
        '^/api/xym': ''
      }
    }
  }
}
```
